service:
  type: ClusterIP
  port: 9100

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

podLabels:
  job: node-exporter

# For EKS: tolerations and affinity to run on all nodes
tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "node-role.kubernetes.io/master"
    operator: "Exists"
    effect: "NoSchedule"

rbac:
  create: true

serviceMonitor:
  enabled: true
  interval: 30s
