architecture: standalone
auth:
  enabled: false
master:
  persistence:
    enabled: false
  service:
    type: ClusterIP
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 200m
