apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: http-01-production
spec:
  acme:
    # Let's Encrypt production ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    email: your-email@example.com   # Replace your email
    privateKeySecretRef:
      name: http-01-production-cluster-issuer
    solvers:
    - http01:
        ingress:
          ingressclassName: nginx-ingress
